title: Arti Gaund # your name (or website title) here
logo: "F:\photo\my\_20180805_115326.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  This is my protfoli which contains my work
  <br><br>
  I am a Website Design Developer and Android Application Developer
  <br><br>
  <a href="https://www.linkedin.com/in/arti-gaund-a6a153170/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
